services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cloudtune-api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp  # Игнорируем временную папку хот-релоада
    environment:
      - PORT=8080
      - ENV=development
    working_dir: /app
    command: air