name: cloudtune_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.3+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  form_field_validator: ^1.1.0
  file_picker: ^8.0.0+1
  permission_handler: ^11.4.0
  path: ^1.9.0
  path_provider: ^2.1.4
  just_audio: ^0.9.40
  audio_service: ^0.18.18
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/logo.jpg
  min_sdk_android: 21
  adaptive_icon_background: "#c9c9cb"
  adaptive_icon_foreground: assets/branding/logo.jpg
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/branding/logo.jpg
  android_12:
    color: "#ffffff"
    image: assets/branding/logo.jpg
  web: false

